// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WineView2.DataAccess.Data;

#nullable disable

namespace WineView2.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240523203928_NewInitialMigration")]
    partial class NewInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WineView2.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rose"
                        },
                        new
                        {
                            Id = 3,
                            Name = "White"
                        });
                });

            modelBuilder.Entity("WineView2.Models.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price10")
                        .HasColumnType("float");

                    b.Property<double>("Price5")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("Wines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 1,
                            ImageUrl = "",
                            Name = "Fortune of Time",
                            Price = 90.0,
                            Price10 = 80.0,
                            Price5 = 85.0
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 1,
                            ImageUrl = "",
                            Name = "Dark Skies",
                            Price = 30.0,
                            Price10 = 20.0,
                            Price5 = 25.0
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 1,
                            ImageUrl = "",
                            Name = "Vanish in the Sunset",
                            Price = 50.0,
                            Price10 = 35.0,
                            Price5 = 40.0
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 2,
                            ImageUrl = "",
                            Name = "Cotton Candy",
                            Price = 65.0,
                            Price10 = 55.0,
                            Price5 = 60.0
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 2,
                            ImageUrl = "",
                            Name = "Rock in the Ocean",
                            Price = 27.0,
                            Price10 = 20.0,
                            Price5 = 25.0
                        },
                        new
                        {
                            Id = 6,
                            ColorId = 3,
                            ImageUrl = "",
                            Name = "Leaves and Wonders",
                            Price = 23.0,
                            Price10 = 20.0,
                            Price5 = 22.0
                        });
                });

            modelBuilder.Entity("WineView2.Models.Wine", b =>
                {
                    b.HasOne("WineView2.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");
                });
#pragma warning restore 612, 618
        }
    }
}
